config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  devise_for :users

  resources :users
  resources :rooms do
    post :messages, to: 'messages#create'
  end

  root to: "rooms#index"

  post '/rooms/:id', to: 'messages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages

  validates :name, presence: true
  scope :sorted, lambda {order("name ASC")}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all.sorted
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    set_room
    @message = Message.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    set_room
    render('edit')
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to("#{room.name}", room_path(room)) %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>

  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<%= form_with url: room_messages_path(@room), local: false do |f| %>
  <%= f.text_area :body, class: "form-control", autofocus: true %>
  <%= f.submit "Say it!" %>
<% end %>
<div class='messageView'>

<%= render partial: "messages/message", collection: @room.messages %>

</div>

<script type="text/javascript">

function scroll(){
  var objDiv = document.querySelector(".messageView");
  //scroll to the top of the scroll height
  objDiv.scrollTop = objDiv.scrollHeight;
}

//this is fired after the page loads, with room id as argument, and scroll as the second callback argument
function initMessages(room, cb){
  scroll();
  // the user becomes a subscriber here by creating a subscription to a given room/channel:
  App.messages = App.cable.subscriptions.create({channel: "BanterChannel", room: room, format: 'html'}, {
    connected: function() {
      // Called when the subscription is ready for use on the server
    },

    disconnected: function() {
      // Called when the subscription has been terminated by the server
    },

    //the data below is coming from the messages/message partial, which in turn came 
    // from the to_html function in the message model
    received: function(data) {
       // Called when there's incoming data on the websocket for this channel
      console.log(data);
      console.log(data.message);
     //the next line selects the div with class messageView, and appends the new message to it
      document.querySelector(".messageView").innerHTML += data.message;
      //the next line clears the text input box, readty for a new next message
      document.querySelector('textarea').value = '';
      //the next line calls the scroll function, but ours is not working atm. lol
      scroll();
      
    }
  });
} 
  

//after the page content has been loaded, this funtion will fire the initMessages function,
//passing in the current room id as an argument
document.addEventListener('DOMContentLoaded', function(){
    initMessages(<%= @room.id %>);
  });

</script>